#!/usr/bin/env python3
"""Genera un dashboard departamental de calidad de vida con datos trazables."""
from pathlib import Path
import json
import duckdb

BASE = Path(__file__).resolve().parent
OUT = BASE / "calidad_vida_dashboard.html"

def main():
    con = duckdb.connect()
    try:
        fies = con.execute("""SELECT Departamento AS departamento,
            Inseguridad_Moderada_Grave_Pct AS inseguridad,
            Inseguridad_Grave_Pct AS inseguridad_grave,
            Área AS area, Fuente AS fuente
            FROM read_parquet(?) WHERE Departamento <> 'Total nacional'""",
            [str(BASE / "plata/fies_2025_rural_prevalencia.parquet")]).fetchdf()
        geih = con.execute("""
        WITH vivienda AS (
          SELECT DPTO AS dpto,
            AVG(TRY_CAST(total_de_personas_en_el_hogar AS DOUBLE)) personas_hogar,
            AVG(CASE WHEN lower(CAST(con_cuales_de_los_siguientes_servicios_cuenta AS VARCHAR)) IN ('1','si','sí') THEN 1 ELSE 0 END)*100 energia,
            AVG(CASE WHEN lower(CAST(con_cuales_de_los_siguientes_servicios_cuenta_3 AS VARCHAR)) IN ('1','si','sí') THEN 1 ELSE 0 END)*100 acueducto,
            AVG(CASE WHEN lower(CAST(con_cuales_de_los_siguientes_servicios_cuenta_5 AS VARCHAR)) IN ('1','si','sí') THEN 1 ELSE 0 END)*100 basuras,
            AVG(CASE WHEN lower(CAST(con_que_energia_o_combustibe_cocinan_principalmente AS VARCHAR)) LIKE '%leña%' OR lower(CAST(con_que_energia_o_combustibe_cocinan_principalmente AS VARCHAR)) LIKE '%carbon%' THEN 1 ELSE 0 END)*100 contaminacion
          FROM read_parquet(?) WHERE CAST(CLASE AS VARCHAR) IN ('2','3') GROUP BY DPTO
        ), ingreso AS (SELECT DPTO AS dpto,AVG(TRY_CAST(ingreso_laborales AS DOUBLE)) ingreso_persona FROM read_parquet(?) WHERE CAST(CLASE AS VARCHAR) IN ('2','3') GROUP BY DPTO)
        SELECT v.*,i.ingreso_persona FROM vivienda v LEFT JOIN ingreso i USING(dpto)
        """, [str(BASE / "plata/geih_2025_decodificada/*__datos_del_hogar_y_la_vivienda.parquet"), str(BASE / "plata/geih_2025_decodificada/*__ocupados.parquet")]).fetchdf()
        geo = con.execute("SELECT departamento,SUBSTR(CAST(DIVIPOLA AS VARCHAR),1,2) AS DPTO FROM read_parquet(?) GROUP BY 1,2", [str(BASE / "plata/contexto_municipal_2025.parquet")]).fetchdf()
        fies = fies.merge(geo, on='departamento', how='left')
        fies = fies.merge(geih, left_on='DPTO', right_on='dpto', how='left')
        fies = fies.drop(columns=['dpto'], errors='ignore')
    finally: con.close()
    data = json.dumps(fies.to_dict("records"), ensure_ascii=False, default=lambda _: None)
    html = """<!doctype html><html lang='es'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Calidad de vida territorial · 2025</title><script src='https://cdn.plot.ly/plotly-2.35.2.min.js'></script><style>
    :root{--ink:#17324d;--muted:#6c8194;--cream:#f7f4ec;--green:#2f8061;--blue:#2687a6;--amber:#e3a229;--red:#c95b4b;--card:#fffdf8}*{box-sizing:border-box}body{margin:0;color:var(--ink);font:15px Inter,system-ui;background:radial-gradient(circle at 90% 0,#d8eee6,transparent 32%),var(--cream)}main{max-width:1450px;margin:auto;padding:34px}.eyebrow{color:var(--green);font-size:12px;letter-spacing:2px;text-transform:uppercase;font-weight:700}.hero{display:flex;justify-content:space-between;align-items:end;margin-bottom:25px}.hero h1{font-size:clamp(32px,5vw,62px);line-height:1;margin:10px 0;color:var(--ink)}.hero p{color:var(--muted);max-width:760px;font-size:17px}.badge{background:#e6f3ed;color:var(--green);padding:11px 16px;border-radius:30px;font-weight:700}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:16px}.card{grid-column:span 4;background:var(--card);border:1px solid #17324d18;border-radius:22px;padding:20px;box-shadow:0 14px 35px #17324d14}.chart{grid-column:span 6;min-height:400px}.wide{grid-column:span 8}..kpi{font-size:34px;font-weight:800;margin:14px 0;color:var(--green)}.kpi.amber{color:var(--amber)}.label{font-size:13px;color:var(--muted)}.source{font-size:11px;color:var(--muted);margin-top:10px;line-height:1.5}.empty{display:flex;align-items:center;justify-content:center;min-height:250px;color:var(--muted);text-align:center;background:#f1eee5;border-radius:14px;padding:20px}@media(max-width:850px){main{padding:18px}.hero{display:block}.card,.chart,.wide{grid-column:span 12}.badge{display:inline-block;margin-top:15px}}
    </style></head><body><main><section class='hero'><div><div class='eyebrow'>DANE · lectura territorial 2025</div><h1>Calidad de vida<br><span style='color:var(--green)'>con evidencia</span></h1><p>Un tablero para leer alimentación, pobreza, servicios y condiciones ambientales sin confundir datos observados con indicadores pendientes.</p></div><div class='badge'>Departamental · rural/resto</div></section><section class='grid'><article class='card'><div class='label'>Personas promedio por hogar</div><div class='kpi' id='personas'>N/D</div><div class='source'>Fuente pendiente de consolidación GEIH/ENUT por departamento.</div></article><article class='card'><div class='label'>Ingreso promedio por persona</div><div class='kpi'>N/D</div><div class='source'>Fuente pendiente: GEIH · INGLABO y otros ingresos.</div></article><article class='card'><div class='label'>IPM</div><div class='kpi amber'>N/D</div><div class='source'>Fuente pendiente: TerriData. No se muestra como cero.</div></article><article class='card chart wide'><div id='alimentacion'></div><div class='source'>Fuente: <code>plata/fies_2025_rural_prevalencia.parquet</code>, DANE ECV 2025 - FIES, Cuadro 2. Área: centros poblados y rural disperso.</div></article><article class='card chart'><div class='label'>Acceso a servicios</div><div class='empty'>Pendiente de consolidar variables P4030S1–P4030S5 de GEIH por departamento.</div><div class='source'>Fuente prevista: GEIH decodificada · módulo vivienda.</div></article><article class='card chart'><div class='label'>Condiciones ambientales proxy</div><div class='empty'>Pendiente de consolidar P5040, P5050 y P5080.<br><br>No es contaminación medida.</div><div class='source'>Fuente prevista: GEIH decodificada · residuos, agua y combustible.</div></article><article class='card chart wide'><div id='grave'></div><div class='source'>Fuente: FIES 2025. Indicador de inseguridad alimentaria grave en hogares.</div></article></section></main><script>const rows=__DATA__,names=rows.map(r=>r.departamento),theme={paper_bgcolor:'transparent',plot_bgcolor:'transparent',font:{color:'#17324d'},margin:{t:55,r:20,b:90,l:55}};Plotly.newPlot('alimentacion',[{x:names,y:rows.map(r=>r.inseguridad),type:'bar',marker:{color:'#e3a229'},hovertemplate:'%{x}<br>%{y:.1f}%<extra></extra>'}],{...theme,title:'Inseguridad alimentaria moderada o grave (%)',xaxis:{tickangle:-45},yaxis:{title:'Porcentaje'}});Plotly.newPlot('grave',[{x:names,y:rows.map(r=>r.inseguridad_grave),type:'bar',marker:{color:'#c95b4b'},hovertemplate:'%{x}<br>%{y:.1f}%<extra></extra>'}],{...theme,title:'Inseguridad alimentaria grave (%)',xaxis:{tickangle:-45},yaxis:{title:'Porcentaje'}});</script></body></html>""".replace('__DATA__', data)
    extra = """<script>(function(){const a=k=>rows.map(r=>Number(r[k])).filter(Number.isFinite),avg=k=>{const v=a(k);return v.length?v.reduce((x,y)=>x+y,0)/v.length:null},fmt=v=>v==null?'N/D':v.toLocaleString('es-CO',{maximumFractionDigits:1});document.querySelector('#personas').textContent=fmt(avg('personas_hogar'));document.querySelector('#personas').nextElementSibling.textContent='Fuente: GEIH decodificada · P6008.';document.querySelectorAll('.kpi')[1].textContent=avg('ingreso_persona')==null?'N/D':avg('ingreso_persona').toLocaleString('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0});const top=k=>rows.filter(r=>Number.isFinite(+r[k])).sort((a,b)=>b[k]-a[k]).slice(0,10),simple=(id,k,title,color,help)=>{let z=top(k);Plotly.newPlot(id,[{x:z.map(r=>+r[k]).reverse(),y:z.map(r=>r.departamento).reverse(),type:'bar',orientation:'h',marker:{color:color},text:z.map(r=>Number(r[k]).toFixed(1)+'%').reverse(),textposition:'auto',hovertemplate:'%{y}: %{x:.1f}%<extra></extra>'}],{paper_bgcolor:'transparent',plot_bgcolor:'transparent',font:{color:'#17324d'},margin:{t:65,r:25,b:45,l:90},title:{text:title+'<br><sup>'+help+'</sup>',font:{size:16}},xaxis:{title:'Porcentaje de hogares (%)',range:[0,100]},yaxis:{title:''}})};simple('alimentacion','inseguridad','Dónde hay más hogares con inseguridad alimentaria','#e3a229','Los porcentajes más altos aparecen arriba.');simple('grave','inseguridad_grave','Dónde es más grave la inseguridad alimentaria','#c95b4b','Mide hogares que enfrentan inseguridad alimentaria grave.');const av=k=>a(k).reduce((s,v)=>s+v,0)/a(k).length;Plotly.newPlot('servicios',[{x:['Acueducto','Energía','Recolección de basuras'],y:[av('acueducto'),av('energia'),av('basuras')],type:'bar',marker:{color:['#2687a6','#2f8061','#e3a229']},text:[av('acueducto'),av('energia'),av('basuras')].map(v=>v.toFixed(1)+'%'),textposition:'auto'}],{paper_bgcolor:'transparent',plot_bgcolor:'transparent',font:{color:'#17324d'},margin:{t:65,r:25,b:55,l:55},title:{text:'Servicios básicos en los hogares<br><sup>Promedio de cobertura en los departamentos disponibles</sup>',font:{size:16}},yaxis:{title:'Hogares con el servicio (%)',range:[0,100]}});Plotly.newPlot('ambiental',[{x:['Uso de leña o carbón'],y:[av('contaminacion')],type:'bar',marker:{color:'#c95b4b'},text:[av('contaminacion').toFixed(1)+'%'],textposition:'auto'}],{paper_bgcolor:'transparent',plot_bgcolor:'transparent',font:{color:'#17324d'},margin:{t:65,r:25,b:55,l:55},title:{text:'Una señal de presión ambiental<br><sup>No es una medición directa de contaminación</sup>',font:{size:16}},yaxis:{title:'Hogares (%)',range:[0,100]}})})();</script>"""
    html = html.replace('Departamental · rural/resto', 'Rural · centros poblados y rural disperso')
    html = html.replace("<div class='empty'>Pendiente de consolidar variables P4030S1–P4030S5 de GEIH por departamento.</div>", "<div id='servicios'></div>")
    html = html.replace("<div class='empty'>Pendiente de consolidar P5040, P5050 y P5080.<br><br>No es contaminación medida.</div>", "<div id='ambiental'></div>")
    html = html.replace('</script></body></html>', '</script>'+extra+'</body></html>')
    OUT.write_text(html, encoding='utf-8')
    print(f"OK: dashboard creado -> {OUT}")

if __name__ == '__main__': main()
